# Numpy matrix operations

## transpose

## multiplication, sum and substraction

## Determinant

## Inverse of matrix

## Rank of Matrix
- Echelon form and pivot columns

## Eigenvalues and Eigenvectors

## Solving Ax=b
1. Gaussian Elimination
2. Crammer Rule

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print("matrix : 1\n",A,"\n\n matrix : 2\n",B)

matrix : 1
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 matrix : 2
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ans = np.dot(A,B)
print(ans)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [5]:
D = np.array([[1,2,3,4]])
print(D)
print(D.shape)
DT = np.transpose(D)
print(DT)
print(DT.shape)

[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [6]:
ans = np.dot(D,DT)
print(ans)
print(ans.shape)

[[30]]
(1, 1)


In [7]:
A = np.array([
    [1,2,3],
    [7,5,4],
    [1,2,3]])
B = np.array([
    [1,2,3],
    [7,5,4],
    [3,2,3]])

try:
    result = np.linalg.inv(B)
    print(result)
except:
    print("Matrix is not invertible")
print("\n")    
try:
    result = np.linalg.inv(A)
    print(result)
except:
    print("Matrx is not invertible")




[[-0.5         0.          0.5       ]
 [ 0.64285714  0.42857143 -1.21428571]
 [ 0.07142857 -0.28571429  0.64285714]]


Matrx is not invertible


In [8]:
A = np.array([
             [1,2,3],
             [4,5,1],
             [2,3,4]
        ])

determinant = np.linalg.det(A)
print(determinant)

-5.000000000000001


In [9]:
A.flatten()

array([1, 2, 3, 4, 5, 1, 2, 3, 4])

## Gaussian Elimination

In [10]:
def gaussian_elimination(A,b):
    
    print("shape of A",A.shape)
    
    num_row = A.shape[0]
    num_col = A.shape[1]
    
    # system is not symetric (not a square matrix)
    if num_row != num_col:
        if num_row < num_col:
            # +++++++++++++++++++ underdetermined system ---> infinite solution ++++++++++++++++++
            x = np.zeros(num_col)
            for i in range(num_row):
                x[i] = b[i] / A[i, i]
            return x
        
#             A_aug = np.concatenate((A, b.reshape(-1, 1)), axis=1)
#             A_aug = np.linalg.solve(A_aug, np.eye(A_aug.shape[0]))
#             x = A_aug[:, -1]
#             A_aug = np.concatenate((A, b.reshape(-1, 1)), axis=1)
#             print(A_aug)
#             print(np.eye(A_aug.shape[0]))
#             A_aug = np.linalg.solve(A_aug, np.eye(A_aug.shape[0]))
#             print(A_aug)
#             x = A_aug[:, -1]
#             return x
        else:
            # +++++++++++++++++++ overdetermined system ---> no unique solution +++++++++++++++++++
            # num_row > num_col (normally our Dataset follow this)
#      1. find solution directly................
            Q, R = np.linalg.qr(A)
            x = np.linalg.solve(R, Q.T @ b)
            print("solution by use of library ====> ",x)
#             or
#      2. find by using linear algebra...........
            AT = np.transpose(A)
            ATA = np.dot(AT,A)
            ATb = np.dot(AT,b)
            try:
                ATA_inverse = np.linalg.inv(ATA)
#                 print("inverse of given input matrix ATA",ATA_inverse)
            except:
                print(f"determinant of ATA is ---> {np.linalg.det(ATA)}")
                return None
            
            result = np.dot(ATA_inverse,ATb)
            print("solution by solving LA ===> ",result)
            return result
#             solve X^TXW = X^Tb ----> W = (X^TX)^-1 *(X^Tb)
            
    else:
        # ++++++++++++++ square matrix ----> unique solution +++++++++++++++
        
        # Eliminate the leading variable in each row of the matrix A.
        for i in range(0,num_row-1):
            for j in range(i+1, num_row):
                pivot = A[i,i]
                element_val = A[j,i]
                pivot = A[i,i]
                val_for_other_cols = A[i,:]
                A[j,:] = A[j,:] - val_for_other_cols*(element_val/pivot)
        print(f"\n\n\nfinal matrix : {A}")
        x = np.zeros(num_row)
        for i in range(num_row-1, -1, -1):
            x[i] = (b[i] - np.sum(A[i, i + 1:] * x[i + 1:])) / A[i, i]
        return x   

In [11]:
import numpy as np

problem = 2
system = {1: "over_determined_system",2:"under_determined_system",3:"square_system"}

if system[problem] == "over_determined_system":
    A = np.array([
        [2, 1], 
        [-3,1],
        [-1,1]
        ])
    b = np.array(
        [-1,-2,1]
    )
elif system[problem] == "under_determined_system":
    A = np.array([
        [3, 4,5], 
        [6,8,10],
      
        ])
    b = np.array(
        [7,8]
    )
else:
    A = np.array([
        [2, 3], 
        [2,-1]
    ])
    b = np.array(
        [3, 1]
    )
    

x = gaussian_elimination(A, b)
print(f"solution of {system[problem]} ---> {x}")


shape of A (2, 3)
solution of under_determined_system ---> [2.33333333 1.         0.        ]


In [12]:
A = np.array([[14,-2],[-2,3]])
print(np.linalg.det(A))
print(np.linalg.inv(A))

37.99999999999999
[[0.07894737 0.05263158]
 [0.05263158 0.36842105]]


In [13]:
# print(A[0,:] + A[1,:])
# A[1, :] -= A[0, :] * (A[1, 0] / A[0,0])
# print(A[1,:])

In [14]:
print(A)
print(A.shape)
print(b)
print(b.shape)

[[14 -2]
 [-2  3]]
(2, 2)
[7 8]
(2,)


In [15]:
b = np.array([[1,2,3]])
print(b)
print(np.transpose(b))

[[1 2 3]]
[[1]
 [2]
 [3]]


## How to check LD or LID cloumn ?
1. One solution is to find a Rank of matrix
    - reduce matrix to row echlon form

In [1]:
!python3 -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 3.6 MB/s eta 0:00:003.8 MB/s eta 0:00:01


In [2]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np
A = np.array([
    [14, 0, 11, 3], 
    [22, 23, 4, 7], 
    [-12, -34, -3, -4]
]) 
print(A)
# print(np.rref(A))

[[ 14   0  11   3]
 [ 22  23   4   7]
 [-12 -34  -3  -4]]


In [6]:
import numpy as np

def count_free_columns(A):

  # Reduce the matrix to row echelon form.
#   A_row_echelon_form = np.rref(A)

  # Count the number of columns that do not contain a leading coefficient.
  num_free_columns = 0
  for i in range(A_row_echelon_form.shape[1]):
    if np.all(A_row_echelon_form[:, i] == 0):
      num_free_columns += 1

  return num_free_columns

# Create a matrix.
A = np.array([[2, 1], [3, -1]])

# Find the number of free columns in the matrix.
num_free_columns = count_free_columns(A)

# Print the result.
print(num_free_columns)

NameError: name 'A_row_echelon_form' is not defined

In [ ]:
import numpy as np

# Create a matrix.
A = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]])

# Calculate the rank of the matrix.
rank = np.linalg.matrix_rank(A)
# Print the rank of the matrix.
print(rank)

In [ ]:
import numpy as np

# Create a matrix.
A = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

# Calculate the eigenvalues and eigenvectors of the matrix.
w, v = np.linalg.eig(A)

# Print the eigenvalues and eigenvectors of the matrix.
print("Eigenvalues:", w)
print("Eigenvectors:", v)

In [42]:
import numpy as np


A = np.array([
    [1, 2], 
    [2, 3]
])
b = np.array(
    [5, 10]
)

x = np.linalg.solve(A, b)

# Print the solution.
print(x)


[5. 0.]


In [52]:
a = [1,2,3,4,5,6]
a = np.array(a).reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


# Regularization (L1 and L2)
- https://www.analyticsvidhya.com/blog/2016/01/ridge-lasso-regression-python-complete-tutorial/#:~:text=Ridge%20and%20Lasso%20Regression%20are,hyperparameter%20tuning%20and%20cross%2Dvalidation.