## Basic about tensors

In [1]:
import torch
import numpy as np

In [2]:
a = [i for i in range(1,13)]
data = np.reshape(a, (3,4))
print(data)
print(type(data))

tensor = torch.from_numpy(data)
print(tensor)
print(type(tensor))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
<class 'torch.Tensor'>


In [3]:
# x = torch.rand_like(tensor,dtype=torch.float)
# print(x)
shape = (5,5)
r = torch.rand(shape)
print(r)
print(r.device)
print(r.dtype)
print(r.shape)

print(r[:,-1])


tensor([[0.1166, 0.3455, 0.5523, 0.8435, 0.8676],
        [0.4104, 0.1816, 0.2170, 0.0207, 0.7104],
        [0.6889, 0.1578, 0.2488, 0.3763, 0.4896],
        [0.6468, 0.6966, 0.5459, 0.1611, 0.4047],
        [0.3763, 0.8652, 0.1989, 0.8553, 0.1113]])
cpu
torch.float32
torch.Size([5, 5])
tensor([0.8676, 0.7104, 0.4896, 0.4047, 0.1113])


In [4]:
print(torch.cat([tensor,tensor,tensor],dim=1))
print(torch.cat([tensor,tensor,tensor]))
print(torch.stack([tensor,tensor]))

tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])


In [5]:
tensor.matmul(tensor.T)


tensor([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [6]:
tensor

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
from torch import nn
input = torch.randn(32, 1, 5, 5)
# With default parameters
m = nn.Flatten()
output = m(input)
output.size()
# With non-default parameters
m = nn.Flatten(0, 2)
output = m(input)
output.size()

## DataLoader and Dataset

In [9]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

In [ ]:
train_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform = ToTensor()
)

test_data = datasets.FashionMNIST(
    root='data',
    train=False,
    download=True,
    transform=ToTensor()
)

In [39]:
print(type(train_data[31]))
features, lable = train_data[1344]

<class 'tuple'>


In [ ]:
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}
figure = plt.figure(figsize=(8, 8))
cols, rows = 3, 3
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(high=len(train_data), size=(1,)).item()
    img, label = train_data[sample_idx]
    figure.add_subplot(rows, cols, i)
    plt.title(labels_map[label])
    plt.axis("off")
    plt.imshow(img.squeeze(), cmap="gray")
plt.show()